const gplay = require("google-play-scraper");
const categories = [
	// gplay.category.APPLICATION,
	// gplay.category.ANDROID_WEAR,
	// gplay.category.ART_AND_DESIGN,
	// gplay.category.AUTO_AND_VEHICLES,
	// gplay.category.BEAUTY,
	// gplay.category.BOOKS_AND_REFERENCE,
	// gplay.category.BUSINESS,
	// gplay.category.COMICS,
	// gplay.category.COMMUNICATION,
	// gplay.category.DATING,
	// gplay.category.EDUCATION,
	// gplay.category.ENTERTAINMENT,
	// gplay.category.EVENTS,
	// gplay.category.FINANCE,
	// gplay.category.FOOD_AND_DRINK,
	// gplay.category.HEALTH_AND_FITNESS,
	// gplay.category.HOUSE_AND_HOME,
	// gplay.category.LIBRARIES_AND_DEMO,
	// gplay.category.LIFESTYLE,
	// gplay.category.MAPS_AND_NAVIGATION,
	// gplay.category.MEDICAL,
	// gplay.category.MUSIC_AND_AUDIO,
	// gplay.category.NEWS_AND_MAGAZINES,
	// gplay.category.PARENTING,
	// gplay.category.PERSONALIZATION,
	// gplay.category.PHOTOGRAPHY,
	// gplay.category.PRODUCTIVITY,
	// gplay.category.SHOPPING,
	// gplay.category.SOCIAL,
	// gplay.category.SPORTS,
	// gplay.category.TOOLS,
	// gplay.category.TRAVEL_AND_LOCAL,
	// gplay.category.VIDEO_PLAYERS,
	// gplay.category.WATCH_FACE,
	// gplay.category.WEATHER,
	// gplay.category.FAMILY,
	// gplay.category.GAME,
	// gplay.category.GAME_ACTION,
	// gplay.category.GAME_ADVENTURE,
	// gplay.category.GAME_ARCADE,
	// gplay.category.GAME_BOARD,
	// gplay.category.GAME_CARD,
	// gplay.category.GAME_CASINO,
	// gplay.category.GAME_CASUAL,
	// gplay.category.GAME_EDUCATIONAL,
	// gplay.category.GAME_MUSIC,
	// gplay.category.GAME_PUZZLE,
	// gplay.category.GAME_RACING,
	gplay.category.GAME_ROLE_PLAYING,
	gplay.category.GAME_SIMULATION,
	gplay.category.GAME_SPORTS,
	gplay.category.GAME_STRATEGY,
	gplay.category.GAME_TRIVIA,
	gplay.category.GAME_WORD,
];

module.exports = categories;
